# -*- coding: utf-8 -*-
"""Actividades de producto.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ujCsVF8ZoYIAc7hRMYNmv7fJKM9ezeSo
"""

# Crear un programa que pida al usuario una contraseña, de forma repetitiva mientras que no introduzca "1234

clave_real = 1234

contraseña = int(input("ingrese contraseña"))
while contraseña != clave_real:
  print(f"contraseña incorrecta, intenta otra vez")
  contraseña = int(input("ingrese contraseña"))


if contraseña == clave_real:
  print(f"Bienvenido")

# Crea un programa que genere dos números al azar entre el 0 y el 100 ...
import random
Num_1 = random.randint(0,100)
Num_2 = random.randint(0,100)
Suma_correct = Num_1 + Num_2
Suma_usuario = int(input(f"¿Cuánto es la suma de el {Num_1} y el {Num_2}?:"))

while True:
    if Suma_usuario == Suma_correct:
        print("Has acertado")
        break
    else:
        print("Has fallado")
        Suma_usuario = int(input(f"¿Cuánto es la suma de el {Num_1} y el {Num_2}"))