# -*- coding: utf-8 -*-
"""Taller proyecto.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fEyFupgo6guXQoAy8uKIB3nsaQFE_LaD

Calculadora de propinas, enlace pantallazo:
"""

import tkinter as tk

# Crear la ventana
ventana = tk.Tk()
ventana.geometry("400x300")  # Aumentamos el ancho de la ventana
ventana.title("Calculadora de propinas")
ventana.configure(bg='light gray')  # Cambiamos el color de fondo a light gray
ventana.attributes("-alpha",1)

def calcular_propina():
    monto_total = float(monto_total_entry.get())
    propina = monto_total * 0.10
    etiqueta_propina.config(text=f"Propina: {propina:.2f}")
    boton_calcular_propina.config(text="Finalizado")

def recalcular():
    monto_total_entry.delete(0, tk.END)
    etiqueta_propina.config(text="Propina: ")
    boton_calcular_propina.config(text="Calcular 10% del total")

def agregar_digito(digito):
    monto_total_entry.insert(tk.END, digito)

# Crear una etiqueta y un campo de entrada para el monto total
monto_total_label = tk.Label(ventana, text="Monto total de la cuenta:")
monto_total_label.pack()
monto_total_entry = tk.Entry(ventana)
monto_total_entry.pack()

# Crear un frame para los cuadritos de dígitos
digitos_frame = tk.Frame(ventana, bg='light gray')
digitos_frame.pack(side=tk.LEFT, padx=20)

# Crear los 9 cuadritos de dígitos
digitos = []
for i in range(9):
    digito = tk.Button(digitos_frame, text=str(i+1), width=2, command=lambda i=i+1: agregar_digito(i))
    digito.grid(row=i//3, column=i%3, padx=5, pady=5)
    digitos.append(digito)

# Crear un botón para el cero
boton_digito_0 = tk.Button(digitos_frame, text="0", width=2, command=lambda: agregar_digito(0))
boton_digito_0.grid(row=3, column=0, padx=5, pady=5)
digitos.append(boton_digito_0)

# Crear un botón para calcular la propina
boton_calcular_propina = tk.Button(ventana, text="Calcular 10% del total", command=calcular_propina)
boton_calcular_propina.pack(padx=50, pady=70)

# Crear una etiqueta para mostrar el resultado
etiqueta_propina = tk.Label(ventana, text="Propina: ")
etiqueta_propina.pack()

# Agregamos un botón extra para recalcular
boton_recalcular = tk.Button(ventana, text="Click para volver a calcular otra cuenta", command=recalcular)
boton_recalcular.pack(side=tk.RIGHT)

# Mostrar la ventana
ventana.mainloop()