# -*- coding: utf-8 -*-
"""Actividades desempeño Taller 2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hWM35UAduMottufYCcbCLfGog5Yectkv

Aplicación de la estructura MATCH CASE
"""

def calcular(operador, a, b):
    match operador:
        case 's':
            return a + b
        case 'r':
            return a - b
        case 'p':
            return a * b
        case 'd':
            if b != 0:
                return a / b
            else:
                return "Error: No se puede dividir por cero."
        case _:
            return "Operador no válido."

#
print(calcular('s', 5, 3))  # Suma
print(calcular('r', 7, 2))  # Resta
print(calcular('p', 4, 6))  # Multiplicación
print(calcular('d', 8, 2))  # División

"""La empresa “PRINTFACIL S.A de C.V” se dedica a vender impresoras con sistema de tinta continuo a un precio unitario de $80000 (sin IVA). Se le pide que realice un algoritmo y a su vez la prueba de escritorio que permita ingresar la cantidad de impresores a comprar y seleccionar la forma de pago para luego generar el detalle del pago a realizar.

Según la forma de pago, la empresa realiza los siguientes descuentos: Finalmente, el programa debe mostrar:

La cantidad de impresoras a comprar.

El precio unitario de la impresora (con IVA).

 El total sin descuento.  La forma de pago.  El descuento realizado.  El total a pagar.

Considere que todos los descuentos se realizan sobre el precio CON IVA. Las entradas del programa deben estar validadas de tal forma que si el usuario ingresa datos incorrectos se debe generar un mensaje de error descriptivo.
"""

def tienda(tipo_pago, precio, impr):
  iva = 0.19
  match tipo_pago:
        case 'efectivo':
             result = precio * impr
             result_iva = (result * iva) + result
             a = result_iva - (result_iva * 0.1)
             print(f"el total sin descuento es {result_iva}")
             print(f"la forma de pago es {tipo_pago} ")
             print(f"el descuento realizado es 10%")
             print(f"el total  pagar es {a}")
        case 'tarjeta':
             result = precio * impr
             result_iva = (result * iva) + result
             a = result_iva - (result_iva * 0.05)
             print(f"el total sin descuento es {result_iva}")
             print(f"la forma de pago es {tipo_pago} ")
             print(f"el descuento realizado es 5%")
             print(f"el total  pagar es {a}")

        case 'vale':
             result = precio * impr
             result_iva = (result * iva) + result
             a = result_iva - (result_iva * 0.15)
             print(f"el total sin descuento es {result_iva}")
             print(f"la forma de pago es {tipo_pago} ")
             print(f"el descuento realizado es 15%")
             print(f"el total  pagar es {a}")


        case _:
            return "Operador no válido."

print(tienda('efectivo', 80000, 2 ))
print(tienda('tarjeta', 80000, 2 ))
print(tienda('vale', 80000, 2 ))
print(tienda('h', 80000, 2 ))