# -*- coding: utf-8 -*-
"""Actividades de Desempeño Taller 3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sjvLdA_2eW5jFt-r2df5eZI9l3C2amrC

Actividades de Desempeño / Taller 3 (While)
"""

""" 1. Elabore un programa que permita mostrar el sueldo promedio de un grupo de empleados"""

# lista de empleados

l_e=[3,8,5]
aux=0
for e in range(0,3):
  aux=l_e[e]+aux
print(f"el promedio es{aux/3}")

""" 2. Elabore un programa que muestre la potencia de 2 de un numero x mientras llegue a 1000"""

# para no alargar tanto el resultado en la ejecucion remplace al 1000 por un 10, (pero es lo mismo)

x= int(input("ingrese numero"))
for i in range(x,10+1):

# ahora muestro la potencia del numero elevado al cuadrado.

  print(i**2)

""" 3. Elaborar un programa que permita ingresar 10 letras y luego nos indique
 al final cuantas vocales y consonantes se ingresaron."""

s=[]
contador=0
contador_v=0
contador_c=0
while contador<10:
  s.append(input('ingrese una letra'))
  contador+=1
print(s)
print(s)
lista_vocales=['a','e','i','o','u']
for j in s:
  if j in lista_vocales:
    print(f"{j} es vocal")
    contador_v+=1

  else:
    print(f"{j} es consonanate")
    contador_c+=1
print(f"el total de consonates es {contador_c}")
print(f"el total de vocales es {contador_v}")

"""4. Debes crear un programa que calcule los resultados de las elecciones
para elegir al alcalde, en las cuales hay tres candidatos compitiendo.
Se considera que hay un total de 200 electores, y todos emitieron su voto.
El programa debe determinar al ganador utilizando el criterio de mayoría simple."""

# programa calculador de quien tuvo mas numero de votos (que operacion? < o > )
# de esos 3 uno solo va a tener mas votos

# votaciones totales hechas = 200, (debe cumplir esta cantidad)

# por ultimo muestra resultado canditado ganador por mayoria

# candidatos = ["Jorge", "Andres", "Camilo"]     (c1 = 68, c2 = 67, c3 = 65) = 200 votos

c1 = int(input("Ingresa los votos que tuvo Jorge:"))
c2 = int(input("Ingresa los votos que tuvo Andres:"))
c3 = int(input("Ingresa los votos que tuvo Camilo:"))

if c1 + c2 + c3 != 200:
    print(f"error, hay mas o menos de 200 votos, la votacion no es valida")
else:

    if c1 > c2 and c1 > c3:
          print(f"El candidato ganador es Jorge")
    elif c2 > c1 and c2 > c3:
          print(f"El candidato ganador es Andres")
    elif c3 > c1 and c3 > c2:
          print(f"El candidato ganador es Camilo")

"""5.Una ONG tiene puntos de reparto de vacunas que se pretende funcionen
de la siguiente manera. Cada día, empezar con 1000 vacunas disponibles
y a través de un programa que controla las entregas avisar si el
inventario baja de 200 unidades. Desarrollar el algoritmo."""

# Solicitar al usuario que ingrese la cantidad inicial de vacunas

inventario_total = int(input("Ingrese la cantidad inicial de vacunas: "))
contador = inventario_total

# Bucle para verificar constantemente el inventario
while True:
    # Verificar si el inventario es igual o menor a 200
    if contador <= 200:
        print("¡Alerta! ya quedan 200 vacunas en el inventario.")
        break  # Salir del bucle

    # Simular el consumo de vacunas
    uso_vacunas = int(input("Ingrese la cantidad de vacunas utilizadas hoy: "))
    contador -= uso_vacunas

""" 6 .Un vivero forestal actualiza cada seis meses los precios de la planta que vende
en función de los valores oficiales de inflación mensual. Desean desarrollar un programa
 que proporcione el precio actualizado a partir del precio anterior y los valores de inflación."""

# cada 6 meses actualiza precios
# valores de inflacion mensual = 12%
# a partir de precio anterior se da el precio actualizado
# programa que proporcione el precio actualizado

inflacion = 0.12
contador = 1
precio = 8000   # float(input("Ingrese el precio planta: "))
while inflacion < 0.16:
    resultado = (precio * inflacion) + precio
    print(f"el precio del semestre {contador} es {resultado} ")

    inflacion += 0.01
    contador += 1

#7.	Desarrolle un programa que calcule el promedio de edad hombre y mujeres de un grupo de estudiantes.
lista_h = [4, 5, 6, 7]
lista_m = [8, 9, 10, 11]
suma = 0
suma_m = 0
contador = 0
p=len(lista_h)
p_2=len(lista_m)
while contador<len(lista_h):
     suma += lista_h[contador]
     suma_m += lista_m[contador]
     contador += 1
print(f"el promedio de los hombres es :{suma/p}")
print(f"el promedio de los mujeres es :{suma_m/p_2}")

#8.	Realice un programa que permita realizar un bingo digital
import random

bingo1 = 0
bingo2 = 0

# Suponiendo que 'bingo_1' y 'bingo_2' son listas con los números ganadores de cada juego
bingo_1 = [1, 2, 3]
bingo_2 = [4, 5, 6]

while bingo1 != "BINGO1" and bingo2 != "BINGO2":  # El bucle debe continuar hasta que uno de los jugadores gane

    contador = 0
    s = []

    while contador < 3:  # Generar una lista de tres números aleatorios para cada juego
        numero_aleatorio = random.randint(1, 10)
        s.append(numero_aleatorio)
        contador += 1

    print("Números generados para bingo1:", s)

    # Comprobar si bingo1 gana
    if s == bingo_1:
        print("¡El ganador es el bingo1!")
        bingo1 = "BINGO1"

    print("Números generados para bingo2:", s)

    # Comprobar si bingo2 gana
    if s == bingo_2:
        print("¡El ganador es el bingo2!")
        bingo2="BINGO2"

# 9
lista_consumo_servicios = [200,300,400,500,600,700,800,900,800,300,100,200]
lista_meses = ["Ene", "Feb", "Mar", "Abr", "May", "Jun", "Jul", "Ago", "Sep", "Oct", "Nov", "Dic"]

suma = 0
z = 0

while z < len(lista_consumo_servicios):
    suma = suma + lista_consumo_servicios[z]

    print(f"el valor a pagar de el mes en: {lista_meses[z]} es : {suma}")
    z += 1
print("Los elementos del consumo mensual son:")
print(lista_consumo_servicios)
print(f"Durante el año ha pagado por concepto de servicios el siguiente valor: {suma}")

""" 9. Considerando que el consumo de servicios de públicos de un establecimiento ha venido
aumentando el alcalde de la ciudad requiere de un programa que le permita saber cuánto ha
 pagado al año y por mes le muestre cuanto paga para poder tener un control de su gasto para
  este concepto. """

# servicios han aumentado
# programa para saber cuanto ha pagado esos 12 meses
# y cuanto debe pagar cada mes

#consumo  aumenta en 5%
# servicios normalmente llegan en 300.000
# aumentar a 300.000 el 5% mas cada mes

consumo_inicial = 300000
aumento_porcentaje = 5 / 100  # 5%
meses = 12

for mes in range(1, meses + 1):
    aumento = consumo_inicial * aumento_porcentaje
    consumo_inicial += aumento
    print(f"Mes {mes}: Aumento = {aumento:.2f}, Consumo Total = {consumo_inicial:.2f}")

"""10. Desarrolle un programa que permita saber el salario de 20 empleados por mes se requiere
el promedio de estos y el pago de cado uno de igual manera cuanto ganaran si se hace un incremento del 2.5%"""

lista_salario_empleados = [78567, 112345, 46890, 142156, 98216, 55364, 134863, 67892, 122365, 89654, 105216, 43567, 116789, 76543, 138987, 95234, 58678, 128345, 72156, 103456]
suma_salario = 0
aumento_salario = 0.025
lista_meses = ["Ene", "Feb", "Mar", "Abr", "May", "Jun", "Jul", "Ago", "Sep", "Oct", "Nov", "Dic"]

for i in range(len(lista_meses)):
  for salario in lista_salario_empleados:
      sum_salario =+ salario

  promedio = sum_salario/len(lista_salario_empleados)
  print (f"El promedio de {lista_meses[i]} salario de los 20 empleados es {promedio}")
  for x in range(len(lista_salario_empleados)):
      lista_salario_empleados[x] =  lista_salario_empleados[x] * aumento_salario + lista_salario_empleados[x]
  print (lista_salario_empleados)