# -*- coding: utf-8 -*-
"""Actividades de desempeño - Taller 1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Zw0_zqy5l8h01iUO-pO9tpPNRAtTejPa

Actividades de desempeño / Taller 1
"""

""" 1. Pide al usuario que ingrese una palabra o frase y usa un ciclo for para contar cuántas vocales
(a, e, i, o, u) contiene. Luego, muestra el conteo de cada vocal por separado"""

contador=0
palabra= str(input("Ingresa una palabra:"))
lista_vocales=['a','e','i','o','u']
for i in palabra:
  if i in lista_vocales:
    contador+=1
print(f"esta palabra tiene {contador} vocales:")

""" 2. Escribe un programa que lea una lista de nombres e imprima la lista en orden alfabético."""

lista_nombres=['daniel','juan','pedro','amanda']
lista_ordenada=[]
for i in lista_nombres:
  lista_ordenada.append(i)
  lista_ordenada.sort()
print(lista_ordenada)

""" 3. Escribe un programa que lea una lista de palabras e imprima la
lista de palabras que comiencen con una determinada letra."""

Lista_palabras = ["Amor", "Paz", "Vida", "Solidaridad", "Temor", "Sabiduría", "Felicidad", "Esperanza", "Alegría", "Amistad"]
for palabra in Lista_palabras:
    if palabra[0] == "A":
      print(palabra)

palabra = []
Lista_palabras = ["burro", "vaca", "carro", "casa", "perro", "gato", "mesa", "silla", "libro", "agua",
                  "ventana", "computadora", "televisor", "teléfono", "camión",
                  "elefante", "jirafa", "dinosaurio", "helado", "playa"]
lista = [Lista_palabras]
lista.append(palabra)
x = input("ingresar letra:")
for palabra in Lista_palabras:
    if palabra[0] == x :
       print(palabra)

""" 4.Escribe un programa lea una lista de números e imprima la suma de los números pares"""

lista_numeros=[1,2,3,4,5,6,7,8,9,10]
pares=[]
impares=[]
for i in lista_numeros:
  if i%2==0:
    pares.append(i)
  else:
    impares.append(i)
print(f"los numeros impares son: {impares}")
print(f"los numeros pares son {pares} y su suma es: {sum(pares)}")